### ISSUE TITLE
Can it be used normally? I want to use onedrive to upload files.

### ISSUE THREAD

**Issue by bbhxwl** [fabian-thomas/ParanoidOneDriveBackup#1]
Can it be used normally? I want to use onedrive to upload files.

**Comment by fabian-thomas** [comment]
I dont really understand what you mean. Can you explain that further?

The service is used to back up your cloud files to some server. So it just downloads all your cloud files like once a day and keeps the last 10 versions of your whole cloud.

**Comment by bbhxwl** [comment]
> I dont really understand what you mean. Can you explain that further?
> 
> The service is used to back up your cloud files to some server. So it just downloads all your cloud files like once a day and keeps the last 10 versions of your whole cloud.

I want to use net core to call onedrive to upload files to realize my own business backup scheme. It hasn't been found.

**Comment by fabian-thomas** [comment]
Do I understand you correctly that you want to upload files to OneDrive using .NET Core? 
This application only **downloads** your files.

**Comment by fabian-thomas** [comment]
I'm gonna close this issue. If you still have questions contact me again.

**Comment by bbhxwl** [comment]
> I'm gonna close this issue. If you still have questions contact me again.

I will use net core to upload files to onedrive.
